name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        backend: [sdl, sokol]
        optimize: [Debug]
    name: Zig Build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0

    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install \
          build-essential \
          libasound2-dev \
          libpulse-dev \
          libaudio-dev \
          libjack-dev \
          libsndio-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxfixes-dev \
          libxi-dev \
          libxss-dev \
          libxkbcommon-dev \
          libdrm-dev \
          libgbm-dev \
          libgl1-mesa-dev \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          libdbus-1-dev \
          libibus-1.0-dev \
          libudev-dev \
          fcitx-libs-dev

    - name: Build Linux
      run: zig build -Dplatform_backend=${{ matrix.backend }} -Doptimize=${{ matrix.optimize }}

    - name: Build Windows
      run: zig build -Dplatform_backend=${{ matrix.backend }} -Doptimize=${{ matrix.optimize }} -Dtarget=x86_64-windows

    - name: Build Wasm32
      run: zig build -Dplatform_backend=${{ matrix.backend }} -Doptimize=${{ matrix.optimize }} -Dtarget=wasm32-emscripten

